name: Youtube Music - Recently listed
on:
  # Schedule daily updates
#   schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.music.svg
          token: NOT_NEEDED
          base: ""
          plugin_music_token: ${{ secrets.YOUTUBE_MUSIC_TOKENS }}
          plugin_music: yes
          plugin_music_mode: recent
          plugin_music_provider: youtube
